### ISSUE TITLE
Setup raspiKull2 (Workbench/HIL)

### ISSUE THREAD

**Issue by kullken** [Pet-Series/Pet-Mk-IV#2]
**Objective:** 
- Setup a common workbench-RPi as an HIL-test bed (Hardware In the Loop)

**Checklist:**
- [x] Install Raspian melodic
- [x] Install ROS melodic
   - [x] Install ROS packages from Pet-Mk-IV github-project -> ~/ros_ws
         _Consider: What is common vs. What is unique for each Pet?_
   - [x] Custom ROS messages on arduino
- [x] Setup SSH
    - [x] Enable OpenSSH + add keys -> GitHub
      _See also: <#13 Connect target(RPi) systems to github-project via SSH-keys>_
    - [x] Enable OpenSSH + add keys for incoming traffic <- Viktor's "Tenebrous"
    - [x] Enable OpenSSH + add keys for incoming traffic <- Stefan's "Frigolit"
      ~~_See also: <Setting up developing env. on "Frigolit" #24>_~~
    - [x] Enable OpenSSH + add keys for incoming traffic <- Stefan's "Scania/Jobb" (aka "RD0067755")
- [x] Install Arduino IDE + library like NewPing

**Prerequisites:**
- [x] One RPi Ver 2B
- [x] One SD-card 8-16GB
- [x] Screen, Keyboard, Mouse

**Comment by SeniorKullken** [comment]
Done long time ago...
